---
title: "knitr_Report"
author: "Arushi Behera"
date: "2025-02-14"
output: word_document
---
```{r, include=FALSE}
#loading ggplot2 library
library(ggplot2)
```

# Dataset = MPG
```{r, echo=FALSE}
#viewing the data
print(mpg)
```

# 1.Summary of the data 
```{r, echo=FALSE}
#summary of the data
summary(mpg)
```

```{r, include=FALSE}
#loading library dplyr
library(dplyr)
```

# 1.a.Mean of City variable of dataset
```{r, echo=FALSE}
#summary of cty
summarise(mpg, mean(cty))
```

# 1.b.Median of Highway variable of dataset
```{r, echo=FALSE}
#summary of hwy
summarise(mpg, median(hwy))
```

# 2.Plot 1 - Scatter plot
```{r, echo=FALSE}
#plot1
ggplot(data=mpg, mapping=aes(x=cty,y=hwy, colour=class, size=cyl))+
  geom_point(alpha=0.7)+
  labs(x="City", 
       y="Highway", 
       title="Highway vs City")+
  scale_colour_viridis_d(option="B")+
  facet_grid(year~drv)+
  coord_fixed(0.5)+
  theme_bw()+
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.title=element_text(angle=0,hjust=0.5, face="bold"),
    axis.line=element_line(linewidth=0.5),
    axis.line.x=element_line(colour="green"),
    axis.line.y=element_line(color="blue"),
    axis.title=element_text(size=15),
    axis.text=element_text(size=8),
    legend.position="right",
)

```

# 3.Plot 2 - Violin plot
```{r, echo=FALSE}
#plot2
ggplot(mpg, aes(x=class, y=hwy))+
  geom_violin()+
  labs(x="Class",
       y="Highway",
       title="Violin plot")+
  scale_y_continuous(breaks = seq(0, 50, by = 10), limits=c(10,50))+
  theme_classic()+
  theme(
    axis.title=element_text(size=15, color="orange"),
    axis.text.x=element_text(angle=45, hjust=1)
  )
```


